apiVersion: v1
kind: Service
metadata:
  name: {{ include "lambda-vm-ack-operator.fullname" . }}-webhook
  labels:
    {{- include "lambda-vm-ack-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "lambda-vm-ack-operator.selectorLabels" . | nindent 4 }}
