# AWS Configuration
aws.region=${AWS_REGION:us-east-1}
aws.microvm.thread-pool-size=10

# Quarkus Operator SDK
quarkus.operator-sdk.start-operator=true

# Health
quarkus.smallrye-health.root-path=/q/health

# Logging
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.level=${QUARKUS_LOG_LEVEL:INFO}
